---
name: Setup Python

description: Setup Python

runs:
  using: composite
  steps:
    - name: Get current Python version
      run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: "pip"
